name = "teamapp"
main = "src/app.ts"
compatibility_date = "2024-12-05"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "dist"
binding = "Client"
not_found_handling = "single-page-application"


[[d1_databases]]
binding = "DB"
database_name = "teamapp"
database_id = "ee97e382-5ab8-4a6e-8603-ad5c359adb38"
migrations_dir = "src/db/migrations"

[vars]
LOG_LEVEL = "debug"
GITHUB_CLIENT_ID = "your-client-id-here"
GITHUB_CLIENT_SECRET = "your-client-secret-here"
AUTH_SECRET = "abc123"
AUTH_URL = "http://localhost:5173/api/auth"
